// List of possible debate-related keywords categorized by topic
export const keywords = [
    "artificial intelligence", "machine learning", "robotics", "automation", "quantum computing",
    "blockchain", "cybersecurity", "data privacy", "digital transformation", "cloud computing",
    "augmented reality", "virtual reality", "internet of things", "5g technology",
    "biotechnology", "genetic engineering", "space exploration", "medical research",
    "genetic testing", "healthcare technology", "public health", "climate adaptation",
    "privacy", "human rights", "equality", "justice", "moral responsibility",
    "ethics of AI", "freedom of speech", "social justice", "gender equality",
    "corporate responsibility", "discrimination", "child labor", "political corruption",
    "poverty", "democracy", "healthcare access", "mental health", "universal healthcare",
    "vaccines", "healthcare reform", "health inequality", "aging population",
    "chronic diseases", "pharmaceutical industry", "healthcare funding",
    "global warming", "renewable energy", "climate change", "sustainability",
    "environmental protection", "green technology", "biodiversity", "carbon emissions",
    "ecosystem conservation", "deforestation", "plastic pollution", "water scarcity",
    "greenhouse gases", "clean energy", "environmental regulations",
    "capitalism", "socialism", "market regulation", "economic growth",
    "global economy", "income inequality", "unemployment", "global trade",
    "investment", "taxation", "labor rights", "corporate social responsibility",
    "innovation", "entrepreneurship", "globalization", "supply chain",
    "online education", "public education", "quality of education", "standardized testing",
    "student rights", "teacher training", "education policy", "education reform",
    "e-learning", "student debt", "higher education", "educational equity",
    "lifelong learning", "STEM education", "school funding",
    "misinformation", "censorship", "fake news", "social media influence", "privacy",
    "digital footprint", "online identity", "cyberbullying", "online activism",
    "social networks", "internet freedom", "social media regulation",
    "digital addiction", "online communities", "social media marketing",
    "professional sports", "sportsmanship", "athlete's rights", "e-sports",
    "media coverage", "entertainment industry", "movie censorship",
    "celebrity culture", "sports ethics", "doping in sports", "gender in sports",
    "social impact of sports", "fan culture", "media bias", "representation in media",
    "streaming services",
    "free will", "consciousness", "morality", "ethics of technology", "human nature",
    "existentialism", "determinism", "psychology of decision making",
    "cognitive biases", "mental health", "human behavior", "self-awareness",
    "evolutionary psychology", "philosophy of mind", "nature vs. nurture",
];
